In [105]:
from google_play_scraper import app

import pandas as pd

import numpy as np

In [106]:
#Scrape desired number of reviews
#Run kode ini jika ingin scrape data dengan jumlah tertentu. Ganti (misal, ingin scrape sejumlah 1000, maka ganti kode , count = 1000 )

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.tokopedia.tkpd',
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=2500, # defaults to 100
    filter_score_with=5 # defaults to None(means all score) Use 1 or 2 or 3 or 4 or 5 to select certain score
)

In [107]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a16f8708-c95f-419d-b998-ec56a9d0719b,Herry Potter,https://play-lh.googleusercontent.com/a-/ALV-U...,Dengan aplikasi ini belanja jadi lebih mudah t...,5,0,3.242,2023-11-23 17:56:15,"Toppers, terima kasih atas rating yang kamu be...",2023-11-23 18:00:03,3.242
1,f11bdf9d-7c2b-4416-8c5b-59397f91a4d4,M Elang Kuncoro S N,https://play-lh.googleusercontent.com/a-/ALV-U...,Sudah baik dan mudah digunakan hanya saja kura...,5,9,3.242,2023-11-07 07:27:31,Terima kasih sudah mempercayakan Tokopedia seb...,2023-11-07 07:33:03,3.242
2,ce8be2dc-938f-4473-957c-ae9ab942e349,Ratu Doll,https://play-lh.googleusercontent.com/a-/ALV-U...,Tokopedia sangat membantu saya untuk membeli b...,5,4,3.242,2023-11-07 16:49:24,"Hi Toppers, terima kasih untuk rating dan ulas...",2023-11-07 16:53:03,3.242
3,a9a2cfdd-f928-46e9-9655-47352621e996,Muhammad Nashih,https://play-lh.googleusercontent.com/a-/ALV-U...,E-Commerce Terbaik!!! saya sudah memggunaknnya...,5,13,3.242,2023-11-09 14:36:01,Terima kasih sudah mempercayakan Tokopedia seb...,2023-11-09 14:44:04,3.242
4,dede04cf-f573-41bb-93da-fb78e5795e78,Andi Suryawan Nugroho,https://play-lh.googleusercontent.com/a-/ALV-U...,Sangat membantu utk berbelanja tanpa harus kel...,5,1,3.242,2023-11-08 13:22:49,"Hi Toppers, terima kasih untuk rating dan ulas...",2023-11-08 13:33:01,3.242

In [108]:
len(df_busu.index) #count the number of data we got

2500

In [109]:
df_busu[['at', 'content']].head()  #preview userName, rating, date-time, and reviews only

                   at                                            content
0 2023-11-23 17:56:15  Dengan aplikasi ini belanja jadi lebih mudah t...
1 2023-11-07 07:27:31  Sudah baik dan mudah digunakan hanya saja kura...
2 2023-11-07 16:49:24  Tokopedia sangat membantu saya untuk membeli b...
3 2023-11-09 14:36:01  E-Commerce Terbaik!!! saya sudah memggunaknnya...
4 2023-11-08 13:22:49  Sangat membantu utk berbelanja tanpa harus kel...

In [110]:
#Run This Code to Sort the Data By Date 

new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,score,at,content
491,Sahbani.putri @gmail.com,5,2023-11-24 22:49:47,Penanganan masalah nya lemot... Merugikan cost...
1971,dampar sulistyo,5,2023-11-24 18:58:16,cepat & banyak potonga
423,Riski Amelda,5,2023-11-24 18:44:53,optimal buat belanja Best respon dan rekomenda...
296,Kuro Black,5,2023-11-24 18:06:57,"Alhamdulillah, respon cepat TOPED meyelesaikan..."
483,Nizam Romadhoni,5,2023-11-24 16:43:41,sangat memuaskan belanja di sni

In [111]:
my_df = df_busu[['at', 'content']] #get userName, rating, date-time, and reviews only

In [112]:
my_df.to_csv("tokpedpos.csv", index=False, sep=";")